[package]
name = "binwalk-ng"
version = "4.0.0"
edition = "2024"
authors = ["Craig Heffner <heffnercj@gmail.com>", "impervius <63152795+impervius@users.noreply.github.com>"]
license = "MIT"
readme = "CARGO_README.md"
repository = "https://github.com/binwalk-ng/binwalk-ng"
description = "Analyzes data for embedded file types"
keywords = ["binwalk", "firmware", "analysis"]
categories = [
    "security",
    "command-line-utilities",
    "parser-implementations",
    "filesystem",
]

[lints.clippy]
redundant_type_annotations = "warn"
redundant_clone = "warn"
redundant_as_str = "warn"
panic = "warn"
nursery = "warn"

[features]
default = ["entropy-plot"]
entropy-plot = ["dep:entropy", "dep:plotters", "dep:dejavu"]

[dependencies]
log = "0.4.34"
base64 = "0.23.1"
walkdir = "2.5.0"
entropy = { version = "0.4.3", optional = true }
colored = "3.1.1"
terminal_size = "0.4.4"
crc32fast = "1.5.2"
crc32c = "0.6.8"
liblzma = "0.4.8"
bzip2 = "0.6.1"
lzfse = "0.2.0"
rayon = "1.12"
serde_json = "1.0.151"
env_logger = "0.11.11"
flate2 = "1.1.10"
adler2 = "2.0.1"
md-5 = "0.11.0"
miniz_oxide = "0.9.1"
aho-corasick = "1.1.5"
memchr = "2.8.3"
memchr-n = "0.1.8"
serde = { version = "1.0.229", features = ["derive"] }
clap = { version = "4.6.7", features = ["derive"] }
xxhash-rust = { version = "0.8.19", features = ["xxh32"] }
hex = "0.4.3"
delink-ng = { version = "0.2.1", default-features = false }
plotters = { version = "0.3.7", default-features = false, features = [
    "bitmap_backend",
    "bitmap_encoder",
    "line_series",
    "ab_glyph",
], optional = true }
dejavu = { version = "2.37.0", optional = true }
jiff = "0.2.20"
zerocopy = { version = "0.8.28", features = ["derive"] }
u24 = "0.6.0"
rars = "0.10.0"
tar = "0.4"
zstd = "0.14.0"
lz4_flex = "0.14.0"
memmap2 = "0.9.9"

[dependencies.uuid]
version = "1.23.4"
features = [
    "v4",       # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[profile.release]
lto = true

[profile.bench]
debug = true

[[bin]]
name = "binwalk"
path = "src/main.rs"
bench = false

[lib]
bench = false

[[bench]]
name = "gungraun"
harness = false

[dev-dependencies]
tempfile = "3.27.0"
insta = { version = "1.48", features = ["yaml", "redactions"] }
gungraun = "0.20.0"
